name: Question
description: Ask a question or start a discussion
labels: ["question"]
body:
  - type: textarea
    id: question
    attributes:
      label: Question
      description: What would you like to know?
    validations:
      required: true
  - type: textarea
    id: context
    attributes:
      label: Context
      description: Any relevant background or what you've already tried.
    validations:
      required: false
